### ISSUE TITLE
Pouvoir paramétrer via une IHM les entrées analogiques

### ISSUE THREAD

**Issue by deffosic** [TemateuRoslyn/censor-management#44]

**Comment by deffosic** [comment]
* Nommer une voie
* Affecter une unité
* affecter une fréquence d'échantillonnage
* affecter un offset 
* affecter un gain
* Affecter un numéro de série

**Comment by Rushclin** [comment]
Pour le paramétrage des entrées analogiques, j'opte pour :
- On met près de chaque entrée, un bouton pour le paramétrer, 
- Lorsqu'on clique dessus, ça ouvre une fenêtre popup, 
- L'utilisateur aura donc la possibilité de paramétrer l’entrée en entrant juste les informations souhaite. 

Autre solution, faire une page générale pour le paramétrage des entrées, on choisie l’entrée dans une liste deroulante et on entre les autres informations.

**Comment by Rushclin** [comment]
> Pour le paramétrage des entrées analogiques, j'opte pour :
> 
> * On met près de chaque entrée, un bouton pour le paramétrer,
> * Lorsqu'on clique dessus, ça ouvre une fenêtre popup,
> * L'utilisateur aura donc la possibilité de paramétrer l’entrée en entrant juste les informations souhaite.
> 
> Autre solution, faire une page générale pour le paramétrage des entrées, on choisie l’entrée dans une liste deroulante et on entre les autres informations.

J'opte pour la seconde car c'est plus simple
